name: docker-build-workflow
on:
    push:
        branches:
            - main
        tags:
            - v*
    workflow_dispatch:
jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: "Publish image"
              uses: matootie/github-docker@v3.1.0
              with:
                  accessToken: ${{ secrets.GITHUB_TOKEN }}
                  tag: ${{ github.ref_name }}
                  containerRegistry: true
            - name: "Publish image latest"
              uses: matootie/github-docker@v3.1.0
              with:
                  accessToken: ${{ secrets.GITHUB_TOKEN }}
                  containerRegistry: true
            - name: Print Full Image URL
              run: echo ${{ steps.publish.outputs.imageURL }}:${{ github.ref_name }}
