name: next-lint-check
on:
    pull_request:
        branches:
            - develop
jobs:
    run-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.2.2
            - name: Install dependencies
              run: bun install --frozen-lockfile
            - name: Run checks
              run: bun lint
